import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body
        style={{
          background: "linear-gradient(83deg, rgba(210, 235, 183, 1) 28%, rgba(198, 230, 186, 1) 52%, rgba(140, 209, 144, 1) 76%)",
        }}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <Navbar />
        <div className="min-h-screen  ">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
